type: object
properties:
  columns:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        statuses:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              self:
                type: string
                format: uri
            additionalProperties: false
        min:
          type: integer
          format: int32
        max:
          type: integer
          format: int32
      additionalProperties: false
  constraintType:
    type: string
additionalProperties: false
